### ISSUE TITLE
Crash with Sodium

### ISSUE THREAD

**Issue by Wizardon777** [wisp-forest/affinity#23]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Affinity' (affinity) 0.1.3+1.21 with any version that is compatible with:
		 - sodium 0.6.0-beta.2+mc1.21.1
More details:
	 - Mod 'Affinity' (affinity) 0.1.3+1.21 is incompatible with any 0.6.x version of mod 'Sodium' (sodium), but a matching version is present: 0.6.0-beta.2+mc1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Arsoth** [comment]
Have there been any updates on this? Sodium 0.6.0 is out in full release now and unfortunately trying to downgrade to 0.5.11 breaks a _lot_ of stuff in my modpack.

**Comment by Noaaan** [comment]
Yes. The pull request #24 was updated to match up the new release. Expect it to be merged soon:tm:

**Comment by Arsoth** [comment]
Soon was an understatement! Now just need to wait for an updated release! Thanks!

**Comment by gliscowo** [comment]
As I'm sure you've noticed, as of [0.1.6](https://modrinth.com/mod/affinity/version/0.1.6+1.21), Affinity now works with Sodium 0.6.x

Cheers
