### ISSUE TITLE
Crash on terrain loading with any shader pack enabled

### ISSUE THREAD

**Issue by Arsoth** [wisp-forest/affinity#28]
If Affinity and a Shader Pack are enabled, the game crashes on loading terrain with a 
`net.caffeinemc.mods.sodium.client.render.chunk.terrain.TerrainRenderPass` error.

If I disable either one, the game loads fine.

Modlist:
- Affinity [0\.1\.6\+1\.21]
- Cardinal Components API [6\.1\.1]
- Fabric API [0\.109\.0\+1\.21\.1]
- Iris [1\.8\.0\+mc1\.21\.1]
- Lavender [0\.1\.14\+1\.21]
- Sodium [0\.6\.0\+mc1\.21\.1]
- TerraBlender [4\.1\.0\.5]
- Trinkets [3\.10\.0]
- oωo [0\.12\.15\+1\.21]

This is the log for what happens if you enable shaders while already in game: https://mclo.gs/3pY0AWC
This is the log what happens if you enable them before loading a world: https://mclo.gs/NPc6SYt

Shaders tried:
- BSL v8.4
- ComplimentaryReimagined r5.2.2 & r5.3
- MakeUp-UltraFast 9.1

Happy to give any other assistance I can, took a while to figure this one out (especially when I had two instances with the same mods and one worked but the other didn't - I didn't even think about shaders being different at first!).

**Comment by gliscowo** [comment]
Thanks for reporting, this has since been fixed in [0.1.7](https://modrinth.com/mod/affinity/version/0.1.7+1.21.1)
Cheers
